### ISSUE TITLE
mjsunit/es6/classes-subclass-builtins fails on MIPS BE

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#217]
mjsunit/es6/classes-subclass-builtins fails on MIPS BE with following error message:

```
Command: /bbv8-slaves/cavoct3eb-board-2/build/slave/v8-linux-mips-debug-target-edge-no-i18n/build/v8/out/Debug/d8 --test --random-seed=-387311916 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap --allow-natives-syntax /bbv8-slaves/cavoct3eb-board-2/build/slave/v8-linux-mips-debug-target-edge-no-i18n/build/v8/test/mjsunit/mjsunit.js /bbv8-slaves/cavoct3eb-board-2/build/slave/v8-linux-mips-debug-target-edge-no-i18n/build/v8/test/mjsunit/es6/classes-subclass-builtins.js
=== mjsunit/es6/classes-subclass-builtins ===
--- stderr ---
#
# Fatal error in .././src/objects-inl.h, line 3284
# Check failed: !v8::internal::FLAG_enable_slow_asserts || (object->IsLayoutDescriptor()).
#
```

Here is the link to where the failure appears: https://v8.mips.com/bbv8/builders/Target%20-%20big%20-%20Debug%20-%20edge%20-%20no%20i18n/builds/3538/steps/Check/logs/stdio

**Comment by paul99** [comment]
My look at the history shows that it was failing much earlier, started at build 3416.

(It is mixed in with interpreter failures that are now fixed, and with the NaN failure described in https://github.com/paul99/v8m-rb/issues/206)

```
Build --  Git hash
3416  --  678a5583d6e15ee81546f7e4a23a21dc5c    first BAD build  classes-subclass-builtins
3415  --  2a4336d97ae8d22ba4955c083fa7f6e6f3    other fails, not that one.

Path to failing build: 
https://v8.mips.com/bbv8/builders/Target%20-%20big%20-%20Debug%20-%20edge%20-%20no%20i18n/builds/3416
```

Lucky for us those 2 git hashes are sequential, so it seems that 678a5583d6 caused the failure. At a quick look, I did not see the problem. It was not a simple object-layout problem as I had suspected. Maybe this CL reveals some other EB object layout issue.

As you chase this one Miran, be sure you understand how the offsets for certain fields differ on big-endian, for example around line 9901 in objects.h, defining kBitFieldOffset in class JSArrayBuffer. There are many other examples in this file.

**Comment by mkaric** [comment]
The test fails at IsLayoutDescriptor check, which calls IsSmi and it fails there. IsSmi function checks the lsb of a pointer to an object and if it is 0 returns true. This works for little-endian, but for big-endian it seems to check the wrong bit, because the pointer is "reversed". On LE numbers like 0423f080, 0723f080, 0d23f080 are checked in IsSmi function, and on BE d080ad04, d080ad07, d080ad0d, with d080ad07 causing the failure (note only 04, 07 and 0d changes for both LE and BE). Investigating further what causes this.

**Comment by paul99** [comment]
@mkaric I looked this code 2 nights ago, but did not see how this occurs from the CL that starts showing the problem.

From your data above, the values in memory are supposed to be (relatively larger-value) Smi's, but they are written to memory in the wrong byte order, so LSB is set, and they erroneously look like pointers. 

It looks like possibly this CL is now showing us bad data in memory, and we previously did not detect it? 

Looking at classes-subclass-builtins.js, the suspicious thing there: they used ArrayBuffers and TypedArrays. Read up on these online (e.g., https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer). These have definite endianness dependencies (you can read a array of bytes as int32, etc) , and is the reason that we skip many tests on big-endian (anything compiled with emscripten makes EL byte order assumptions, and they actually have an assert that we fail on EB). (https://chromium.googlesource.com/v8/v8/+/93eb633214e0f97bf70ae30d2a07b7fbbaa78266/test/mjsunit/mjsunit.status#380)

So please look carefully at this. My first look is that they seem to map arrays of chars to Int32Array and Uint32Array, and that seems unlikely to work right for EB.

Yet, that code was there and working prior to this CL, so there is some mystery we should understand.

We might have to just add this to skip list.

@lialan can you check this with the IBM folks and see of this test passes on their big-endian? I'm not familiar with any public bots for them. (I think Google's bots are just EL sim PPC)

**Comment by mkaric** [comment]
I managed to make the test a lot shorter, and it still fails with the same error:

```
"use strict";
function TestErrorSubclassing(error) {
  class A extends error {
  }
  var o = new A("message");
}
TestErrorSubclassing(Error);
```

This part of the test generates that '1' on lsb and fails, but incorrect pointer is generated many times in the whole test, only it is not detected as lsb is '0'.

**Comment by paul99** [comment]
@mkaric please see new issue referenced above. I am thinking this might have same root cause as this issue, and there are some suggestions there for debugging. Hope this helps!

**Comment by mkaric** [comment]
Fixed in #220, closing.
